version: '3.8'

services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: "rabbitmq-service-container"
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_PORT_2:-15672}:15672"
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${RABBITMQ_PORT_2:-15672}"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    expose:
      - ${RABBITMQ_PORT}
